program ::= decl*

decl ::= func_decl

func_decl ::= "fn" ident "(" ")" block

block ::= "{" stmt* "}"

stmt ::= println_stmt | expr ";"
println_stmt ::= "println" "!" "(" expr ")" ";"

expr ::= call | integer_literal | byte_str
call ::= ident "(" ")"
