program ::= decl*

decl ::= func_decl

func_decl ::= 'fn' ident '(' func_params ')' block
func_params ::= (ident ',')* ident?

block ::= '{' stmt* '}'

stmt ::= println_stmt | var_decl_stmt | expr_stmt
println_stmt ::= 'println' '!' '(' expr ')' ';'
var_decl_stmt ::= 'let' ident '=' expr ';'
expr_stmt ::= expr ';'

expr ::= expr bin_op expr | unary_op expr | assign | group | call | return
         ident | integer_literal | byte_str
# The precendence of these operators is defined in the code
bin_op ::= '+' | '-' | '*' | '/' | '%'
unary_op ::= '+' | '-' | '!'
assign ::= lvalue '=' expr
lvalue ::= ident
group ::= '(' expr ')'
call ::= expr '(' func_args ')'
func_args ::= (expr ',')* expr?
return ::= 'return' expr
